name: Publish VS Code Extension

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build MCP server and compile extension
        run: |
          npm run build:mcp
          npm run compile

      - name: Run tests
        run: |
          npm test

      - name: Verify package.json version matches tag
        id: ver
        run: |
          TAG=${GITHUB_REF##refs/tags/}
          echo "Release tag: $TAG"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "package.json version: $PKG_VERSION"
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "::error::Release tag ($TAG) does not match package.json version ($PKG_VERSION)."
            exit 1
          fi

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx -y vsce publish --pat "$VSCE_PAT"
